# Generated by Django 4.2.3 on 2023-09-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extantmodel',
            name='department',
            field=models.CharField(default='...', max_length=100),
        ),
    ]
