# Generated by Django 4.2.3 on 2023-09-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_employeeattendance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
